config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :pages
  end

  constraints(Spree::SpreePages::RoutesConstraints) do
    get '/(*path)', to: 'pages#show', as: 'page'
  end
end

app/models/spree/page.rb
module Spree
  class Page < ApplicationRecord
    has_attached_file :meta_image, styles: ->(i) { i.instance.class.meta_image_sizes }
    validates_attachment_content_type :meta_image, content_type: %r{\Aimage\/.*\z}

    validates :title, :slug, :content, presence: true
    validates :slug, uniqueness: true

    scope :live, -> { where(live: true) }

    before_save :remove_leading_slash_from_slug

    def remove_leading_slash_from_slug
      self.slug = slug[1..-1] if slug.start_with?('/') # ensure that slugs don't start with a slash
    end

    private

    def self.meta_image_sizes
      { large: '1200x630>', medium: '600x315>', small: '200x200>' }
    end
  end
end

app/controllers/spree/admin/pages_controller.rb
module Spree
  module Admin
    class PagesController < ResourceController
      private

      def permitted_resource_params
        params.require(:page).permit(%i[title content slug meta_title meta_description meta_image live])
      end
    end
  end
end

app/controllers/spree/pages_controller.rb
module Spree
  class PagesController < StoreController
    def show
      @page =
        if try_spree_current_user&.respond_to?(:has_spree_role?) && try_spree_current_user&.has_spree_role?(:admin)
          Spree::Page.find_by(slug: request.path[1..-1])
        else
          Spree::Page.live.find_by!(slug: request.path[1..-1])
        end

      @title = @page.title
    end
  end
end

app/views/spree/admin/pages/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: resource } %>

<%= form_for [:admin, resource] do |f| %>
  <div class="row" data-hook="admin_page_form_fields">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %> <span class="required">*</span>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :slug %> <span class="required">*</span>
        <%= f.text_field :slug, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :content %> <span class="required">*</span>
        <%= f.text_area :content, rows: 12, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :meta_title %>
        <%= f.text_field :meta_title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :meta_description %>
        <%= f.text_field :meta_description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :meta_image %>
        <%= f.file_field :meta_image %>
        <% if resource.meta_image.exists? %>
          <%= image_tag resource.meta_image.url(:small) %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :live %>
        <%= f.check_box :live %>
      </div>
    </div>
  </div>

  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Page.model_name.human) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Page) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_page), new_object_url, icon: 'plus', class: 'btn-primary', id: 'admin_new_page' %>
<% end %>

<% if @pages.any? %>
  <table class="table" id="listing_pages" data-hook>
    <colgroup>
      <col style="width: 60%">
      <col style="width: 40%">
    </colgroup>
    <thead>
      <tr data-hook="admin_pages_index_headers">
        <th><%= Spree::Page.human_attribute_name(:title) %></th>
        <th data-hook="admin_pages_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even') %>" id="<%= dom_id page %>">
          <td><%= page.title %></td>
          <td class="actions text-right" data-hook="admin_pages_index_row_actions">
            <%= link_to 'Show in app', page_url(page.slug), target: '_blank' %>
            <%= link_to_edit page, no_text: true %>
            <%= link_to_delete page, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::Page.model_name.human) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_page_path %>!
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_page) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/shared/_pages_menu_item.html.erb
<% if can?(:admin, Spree::Page) %>
  <ul class='nav nav-sidebar'>
    <%= tab Spree::Page, url: spree.admin_pages_url, icon: 'font', label: plural_resource_name(Spree::Page) %>
  </ul>
<% end %>

app/views/spree/pages/_og_meta_tags.html.erb
<% content_for(:head) do %>
  <% page_meta_title = page.meta_title.presence || @title %>
  <meta name="title" content="<%= page_meta_title %>">
  <meta property="og:title" content="<%= page_meta_title %>">
  <meta property="og:description" content="<%= page.meta_description || meta_data[:description] %>">
  <% if page.meta_image.exists? %>
    <meta property="og:image" content="<%= page.meta_image.url(:large) %>">
  <% end %>
<% end %>

app/views/spree/pages/show.html.erb
<%= render partial: 'og_meta_tags', locals: { page: @page } %>

<% cache([:v3, @page]) do %>
  <center><h2><%= @page.title %></h2></center>
  <br>
  <div id='page_content'>
    <%= raw @page.content %>
  </div>
<% end %>